### ISSUE TITLE
Data Science with Ruby

### ISSUE THREAD

**Issue by arbox** [smalldatabook/smalldatabook.github.io#1]
Hi Gerald,

thank you for your comments on Reddit. I think we should collaborate on possible topics of Data Science. Let's talk somewhere (English/German). Skype?

Best,
Andrei

**Comment by geraldb** [comment]
@arbox  First thanks for your great awesome lists. Fantastic collections.  Sorry I don't have skype installed. Unfortunately I'm way oversubscribed with open source projects for now - so don't expect too much. See all the awesome ruby pages on [Planet Ruby](https://github.com/planetruby) that would need an update.

 If you're interested in a talk - maybe you can send me a phone number (to gerald.bauer AT gmail.com) and a convenient time, for example, this week and will call (if the time works for both). I'm in Vienna (Central Europe). Cheers.

**(Update)** Sent you reply by email.
